name: docker deleted host testing

on: 
  push:
     branches:
     - main
  pull_request:
     branches:
     - main
     
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Проверить исходный код
      - name: Checkout code
        uses: actions/checkout@v3

      # Установить Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      # Запуск 
      - name: launch docker on deleted host
        run: |
          docker run -d -v ${{ github.workspace }}:/app -p 5000:5000 phynsl/repeat-after-others:latest
          sleep 5 

      - name: Check Docker Container Logs
        run: docker ps -a
          
      - name: fetch
        run: |
          docker ps -q --filter ancestor=phynsl/repeat-after-others:latest | while read container_id; do
              echo "Logs for container $container_id:"
              docker logs $container_id
          done
          
      - name: Test HTTP Response
        run: |
          curl -s http://172.17.0.2:5000 | grep "Hello World!"
