name: docker deleted host testing

on: 
  push:
     branches:
     - main
  pull_request:
     branches:
     - main
     
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Проверить исходный код
      - name: Checkout code
        uses: actions/checkout@v3

      # Установить Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      # Запуск 
      - name: launch docker on deleted host
        run: |
          sudo docker run -d -v ${{ github.workspace }}:/app -p 5000:5000 phynsl/rebuild:v2 /bin/sh
          sleep 5 

      - name: Check Docker Container Logs
        run: sudo docker ps -a
          
      - name: fetch
        run: |
          sudo docker ps -q --filter ancestor=phynsl/rebuild:v2 | while read container_id; do
              echo "Logs for container $container_id:"
              docker logs $container_id
          done

      - name: ping 
        run: |
         sudo ping -c 5 172.17.0.2
      
      - name: Test HTTP Response
        run: |
          sudo curl -s http://172.17.0.2:5000 
